import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  <div className="background-icons">
     <img src="/icons/graph-analysis.png" alt="icon" />
    <img src="/icons/quizz.png" alt="icon" />
    <img src="/icons/question.png" alt="icon" />
    <img src="/icons/presentation.png" alt="icon" />
   
    
  
    <img src="/icons/business-analystt.png" alt="icon" />
    <img src="/icons/business-analyst.png" alt="icon" />
  </div>
  {children}
</body>

    </html>
  );
}
